name: Electron Build and Release

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'flatpak'
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            container: null
          - os: ubuntu-latest
            container: bilelmoussaoui/flatpak-github-actions:gnome-45
            options: --privileged
          - os: macos-latest
            container: null

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Setuptools for Python (macOS only)
        if: matrix.os == 'macos-latest'
        run: pip3 install setuptools --break-system-packages

      - name: Install dependencies
        run: |
          cd electron
          pnpm install --frozen-lockfile

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd electron
          npm run publish

      - name: Build Flatpak
        if: matrix.os == 'ubuntu-latest'
        run: |
          git config --global --add safe.directory /__w/migu/migu
          cd electron
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --noninteractive -y org.freedesktop.Platform/x86_64/23.08
          ../flatpak/update-metainfo.sh
          flatpak-builder --user --install --force-clean build-dir --install-deps-from=flathub --repo=repo ../flatpak/com.github.nocrypt.migu.yaml
          flatpak build-bundle repo dist/com.github.nocrypt.migu.flatpak com.github.nocrypt.migu

      - name: Upload Flatpak Artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: flatpak
          path: electron/dist/*.flatpak
          if-no-files-found: error
