name: Electron Build and Release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            container: null
          - os: ubuntu-latest
            container: bilelmoussaoui/flatpak-github-actions:gnome-nightly
            options: --privileged
          - os: macos-latest
            container: null

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Setuptools for Python (macOS only)
        if: matrix.os == 'macos-latest'
        run: pip3 install setuptools --break-system-packages

      - name: Install dependencies
        run: |
          cd electron
          pnpm install --frozen-lockfile

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd electron
          npm run publish

      - name: Upload Linux AppImage
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: electron/dist/*.AppImage
          if-no-files-found: error
